import { createContext, useContext } from "react";

const translations = {
	uz: {
		// App
		app_name: "KIUT",
		tagline: "Universitet ilmiy faoliyat reyting tizimi",
		univ_name_line1: "KIMYO INTERNATIONAL UNIVERSITY",
		univ_name_line2: "IN TASHKENT",

		// Navigation
		dashboard: "Dashboard",
		teachers: "O'qituvchilar",
		activities: "Faoliyatlar",
		review: "Tekshirish",
		rating: "Reyting",
		reports: "Hisobotlar",
		catalogs: "Kataloglar",
		departments_page: "Kafedralar",
		categories_page: "Kategoriyalar",
		degrees: "Ilmiy darajalar",
		academic_years: "O'quv yillari",
		system: "Tizim",
		public_rating: "Ochiq reyting",
		settings: "Sozlamalar",

		// Common
		edit: "Tahrirlash",
		confirm: "Tasdiqlash",
		send: "Yuborish",
		search: "Qidirish...",
		search_by_name: "Ism bo'yicha qidirish...",
		all: "Barchasi",
		clear: "Tozalash",
		score: "Ball",
		status: "Status",
		actions: "Amal",
		select: "Tanlang",
		loading: "Yuklanmoqda...",
		data_not_found: "Ma'lumot mavjud emas",
		filter: "Filter",
		view: "Ko'rish",
		back: "Orqaga",

		// Statuses
		all_statuses: "Barchasi",
		draft: "Qoralama",
		submitted: "Yuborilgan",
		in_review: "Tekshiruvda",
		revision: "Qayta ishlash",
		approved: "Tasdiqlangan",
		rejected: "Rad etilgan",
		archived: "Arxivlangan",
		pending: "Kutilayotgan",
		reviewed: "Tekshirilgan",

		// Teachers
		teachers_title: "O'qituvchilar",
		teachers_desc: "O'qituvchilar ro'yxatini boshqarish",
		add_teacher: "Qo'shish",
		new_teacher: "Yangi o'qituvchi",
		edit_teacher: "O'qituvchini tahrirlash",
		full_name: "To'liq ism",
		department: "Kafedra",
		all_departments: "Barcha kafedralar",
		position: "Lavozim",
		all_positions: "Barcha lavozimlar",
		academic_degree: "Ilmiy daraja",
		all_degrees: "Barcha darajalar",
		academic_rank: "Ilmiy unvon",
		employment_type: "Ish turi",
		email: "Email",
		phone: "Telefon",
		photo: "Rasm",
		upload_photo: "Rasm yuklash",
		change_photo: "Rasmni o'zgartirish",
		score_range: "Ball",
		teacher_added: "O'qituvchi qo'shildi",
		teacher_updated: "O'qituvchi yangilandi",
		no_teachers: "O'qituvchilar topilmadi",
		no_teachers_desc: "Yangi o'qituvchi qo'shing",
		shtat: "Shtat",
		soatbay: "Soatbay",
		ichki_orindosh: "Ichki o'rindosh",
		tashqi_orindosh: "Tashqi o'rindosh",

		// Activities
		activities_title: "Faoliyatlar",
		activities_desc: "Ilmiy va akademik faoliyatlarni boshqarish",
		new_activity: "Yangi faoliyat",
		edit_activity: "Faoliyatni tahrirlash",
		activity_details: "Faoliyat tafsilotlari",
		title: "Sarlavha",
		category: "Kategoriya",
		date: "Sana",
		academic_year: "O'quv yili",
		reference_url: "Havola (DOI, URL)",
		reference_placeholder: "https://...",
		evidence: "Hujjatlar",
		evidence_files: "Hujjatlar (Evidence)",
		click_to_upload: "Fayl yuklash uchun bosing",
		file_types_hint: "PDF, DOCX, JPG, PNG, XLSX",
		coauthor: "Hammualliflik (50% koeffitsient)",
		coauthor_name: "Hammuallif ismi va familiyasi",
		coauthor_placeholder: "Hammuallif to'liq ismi",
		submit_for_review: "Yuborish",
		activity_added: "Faoliyat qo'shildi",
		activity_updated: "Faoliyat yangilandi",
		submitted_to_review: "Tekshiruvga yuborildi",
		no_activities: "Faoliyatlar topilmadi",
		no_activities_desc: "Yangi faoliyat qo'shing",
		teacher: "O'qituvchi",
		final_score: "Yakuniy ball",
		reviewer_comment: "Tekshiruvchi izohi",
		submitted_by_teacher: "O'qituvchi tomonidan yuborildi",
		coauthor_label: "Hammualliflik",
		files_count: "hujjat",
		files: "Hujjatlar",

		// Review
		review_title: "Tekshirish",
		review_desc: "Faoliyatlarni ko'rib chiqish va tasdiqlash",
		approve: "Tasdiqlash",
		reject: "Rad",
		revision_action: "Qayta",
		confirm_decision: "Qarorni tasdiqlang",
		confirm_approve: "Ushbu faoliyatni tasdiqlamoqchimisiz?",
		confirm_reject: "Ushbu faoliyatni rad etmoqchimisiz?",
		confirm_revision: "Qayta ishlashga yubormoqchimisiz?",
		comment: "Izoh",
		comment_placeholder: "Izoh yozing...",
		review_success: "Muvaffaqiyatli bajarildi",
		no_pending: "Tekshiruv uchun faoliyatlar yo'q",

		// Reports
		reports_title: "Hisobotlar",
		reports_desc: "Statistik hisobotlar va tahlillar",
		export_excel: "Excel",
		excel_exported: "Hisobot CSV faylga eksport qilindi",
		no_export_data: "Eksport uchun ma'lumot mavjud emas",
		departments_report: "Kafedralar",
		categories_report: "Kategoriyalar",
		statuses_report: "Statuslar",
		teachers_count: "O'qituvchilar",
		activities_count: "Faoliyatlar",
		approved_count: "Tasdiqlangan",
		avg_score: "O'rtacha ball",
		dept_chart_title: "Kafedralar bo'yicha ballar",
		cat_chart_title: "Kategoriyalar bo'yicha faoliyatlar",
		status_chart_title: "Statuslar bo'yicha taqsimot",
		year: "Yil",
		month: "Oy",
		quarter: "Chorak",
		week: "Hafta",
		all_years: "Barcha yillar",
		all_months: "Barcha oylar",
		all_quarters: "Barcha choraklar",
		all_weeks: "Barcha haftalar",
		count: "Soni",
		unknown: "Noma'lum",

		// Status labels in reports
		status_draft: "Qoralama",
		status_submitted: "Yuborilgan",
		status_in_review: "Tekshiruvda",
		status_approved: "Tasdiqlangan",
		status_rejected: "Rad etilgan",
		status_revision: "Qayta ishlash",

		// Months
		january: "Yanvar",
		february: "Fevral",
		march: "Mart",
		april: "Aprel",
		may: "May",
		june: "Iyun",
		july: "Iyul",
		august: "Avgust",
		september: "Sentyabr",
		october: "Oktyabr",
		november: "Noyabr",
		december: "Dekabr",
		q1: "1-chorak (Yan-Mar)",
		q2: "2-chorak (Apr-Iyun)",
		q3: "3-chorak (Iyul-Sen)",
		q4: "4-chorak (Okt-Dek)",

		// Departments
		departments_title: "Kafedralar",
		departments_desc: "Kafedralar ro'yxatini boshqarish",
		new_department: "Yangi kafedra",
		edit_department: "Tahrirlash",
		name: "Nomi",
		name_req: "Nomi *",
		code: "Kodi",
		head: "Mudiri",
		dep_added: "Kafedra qo'shildi",
		dep_updated: "Kafedra yangilandi",
		dep_deleted: "Kafedra o'chirildi",
		no_departments: "Kafedralar topilmadi",
		delete_confirm_title: "O'chirishni tasdiqlaysizmi?",
		delete_confirm_desc: "Bu amalni qaytarib bo'lmaydi.",
		head_label: "Mudiri:",

		// Categories
		categories_title: "Kategoriyalar",
		categories_desc: "Ball berish kategoriyalari",
		new_category: "Yangi kategoriya",
		group_req: "Guruh *",
		multiplier_field: "Ko'paytiruvchi",
		penalty_yes: "Ha",
		cat_added: "Kategoriya qo'shildi",
		cat_updated: "Kategoriya yangilandi",
		cat_deleted: "Kategoriya o'chirildi",
		no_categories: "Kategoriyalar topilmadi",
		academic: "Akademik",
		qualification: "Malaka",
		scientific: "Ilmiy",
		other: "Boshqa",
		group_academic_discipline: "Akademik intizom",
		group_qualification: "Malaka va tashkilotchilik",
		group_scientific: "Ilmiy faoliyat",
		group_other: "Boshqa",
		multiplier_short: "Ko'payt.",
		max_short: "Maks.",
		penalty: "Jarima",

		// Degrees & Ranks
		degrees_title: "Ilmiy darajalar va unvonlar",
		degrees_desc: "Kataloglarni boshqarish",
		new_degree: "Yangi daraja",
		new_rank: "Yangi unvon",
		degrees_tab: "Ilmiy darajalar",
		ranks_tab: "Ilmiy unvonlar",
		item_added: "Qo'shildi",
		item_updated: "Yangilandi",
		item_deleted: "O'chirildi",

		// Academic Years
		years_title: "O'quv yillari",
		years_desc: "O'quv yillarini boshqarish",
		years_purpose: "O'quv yillari faoliyatlarni davrlar bo'yicha guruhlash uchun ishlatiladi. Har bir faoliyat ma'lum bir o'quv yiliga biriktiriladi.",
		new_year: "Yangi o'quv yili",
		state: "Holat",
		active_state: "Faol",
		inactive_state: "Nofaol",
		year_placeholder: "2024-2025",
		year_added: "O'quv yili qo'shildi",
		year_updated: "O'quv yili yangilandi",
		year_deleted: "O'quv yili o'chirildi",
		start_label: "Boshlanish",
		end_label: "Tugash",

		// Dashboard
		dashboard_title: "Bosh sahifa",
		dashboard_desc: "Universitet ilmiy faoliyat statistikasi",
		dashboard_desc_short: "Kafedralar bo'yicha ilmiy faoliyat ko'rsatkichlari",
		approved_stat: "Tasdiqlangan",
		total_score: "Jami ball",
		dept_scores_chart: "Kafedralar bo'yicha ballar",
		cat_distribution_chart: "Kategoriyalar taqsimoti",
		pending_reviews: "Kutilayotgan tekshiruvlar",
		no_pending_reviews: "Kutilayotgan tekshiruvlar yo'q",
		recent_activities: "So'nggi faoliyatlar",
		no_recent_activities: "Faoliyatlar mavjud emas",

		// Rating
		rating_title: "Reyting",
		rating_desc: "O'qituvchilar reytingi",
		rank_label: "O'rin",

		// Public Rating
		public_rating_title: "Universitet Reytingi",
		public_rating_desc: "O'qituvchilar ilmiy faoliyat reytingi",
		public_search_placeholder: "Ism bo'yicha qidirish...",
		public_department_placeholder: "Kafedra",

		// Settings
		settings_title: "Sozlamalar",
		settings_desc: "Tizim sozlamalari va boshqaruv paneli",
		roles_tab: "Foydalanuvchi rollari",
		roles_desc: "Tizimda mavjud foydalanuvchi rollari va ularning vazifalari",
		role_admin: "Administrator",
		role_admin_desc: "To'liq boshqaruv huquqi, barcha sozlamalarni o'zgartira oladi",
		role_rector: "Rektor",
		role_rector_desc: "Strategik qarorlar qabul qiladi, barcha hisobotlarni ko'radi",
		role_dean: "Dekan",
		role_dean_desc: "Fakultet faoliyatini boshqaradi, tasdiqlash huquqiga ega",
		role_department_head: "Kafedra mudiri",
		role_department_head_desc: "Kafedra o'qituvchilari faoliyatini boshqaradi va tasdiqlaydi",
		role_teacher: "O'qituvchi",
		role_teacher_desc: "Faoliyat ma'lumotlarini kiritadi va o'z reytingini kuzatadi",
		role_reviewer: "Taqrizchi",
		role_reviewer_desc: "Faoliyatlarni tekshiradi va baholaydi",
		kpi_calc_tab: "KPI hisoblash",
		kpi_calc_title: "KPI hisoblash parametrlari",
		calc_mode: "Hisoblash rejimi",
		calc_auto: "Avtomatik",
		calc_manual: "Qo'lda",
		score_scale_max: "Maksimal ball shkalasi",
		weight_percentages: "Yo'nalishlar vazni (foizda)",
		weight_teaching: "O'qitish",
		weight_scientific: "Ilmiy faoliyat",
		weight_methodical: "Metodik ishlar",
		weight_grants: "Grantlar",
		weight_publications: "Nashrlar",
		weight_supervision: "Rahbarlik",
		kpi_period_start: "KPI davri boshlanishi",
		kpi_period_end: "KPI davri tugashi",
		auto_approve_threshold: "Avtotasdiqlash chegarasi",
		auto_approve_desc: "Ushbu balldan yuqori faoliyatlar avtomatik tasdiqlanadi (0 = o'chirilgan)",
		teacher_types_tab: "O'qituvchi turlari",
		teacher_types_desc: "O'qituvchilarning bandlik turlari",
		shtat_desc: "To'liq stavkada ishlovchi asosiy xodim",
		soatbay_desc: "Soatbay asosida ishlovchi o'qituvchi",
		ichki_orindosh_desc: "Universitet ichidagi qo'shimcha vazifani bajaruvchi",
		tashqi_orindosh_desc: "Tashqi tashkilotdan kelgan o'rindosh",
		academic_years_tab: "O'quv yili sozlamalari",
		academic_year_settings_desc: "Joriy o'quv yillari ro'yxati. Faoliyatlar davrlar bo'yicha guruhlanadi.",
		manage_academic_years: "O'quv yillarini boshqarish",
		categories_tab: "KPI kategoriyalar",
		categories_settings_desc: "Faoliyat turlari va ularning ball qiymatlari",
		manage_categories: "Kategoriyalarni boshqarish",
		degrees_settings_desc: "Ilmiy daraja va unvonlar ro'yxati",
		academic_degrees: "Ilmiy darajalar",
		academic_ranks: "Ilmiy unvonlar",
		manage_degrees: "Daraja va unvonlarni boshqarish",
		dashboard_settings_tab: "Dashboard sozlamalari",
		dashboard_settings_desc: "Bosh sahifa ko'rinishi va funksiyalari",
		show_charts: "Grafiklarni ko'rsatish",
		show_charts_desc: "Kafedra va kategoriya statistikasi grafiklari",
		show_filters: "Filtrlar paneli",
		show_filters_desc: "Hisobotlarda filtr imkoniyatlari",
		enable_export: "Eksport funksiyasi",
		enable_export_desc: "CSV formatda ma'lumotlarni yuklab olish",
		notifications_tab: "Bildirishnomalar",
		notifications_desc: "Tizim bildirishnomalari va ogohlantirishlar",
		deadline_reminder: "Deadline eslatmasi",
		deadline_reminder_desc: "KPI topshirish muddati yaqinlashganda xabar berish",
		approval_notify: "Tasdiqlash bildirishnomalari",
		approval_notify_desc: "Faoliyat tasdiqlanganda yoki rad etilganda xabar berish",
		warning_notify: "Ogohlantirishlar",
		warning_notify_desc: "Kam ball yoki muddati o'tgan faoliyatlar haqida ogohlantirish",
		permissions_tab: "Ruxsatlar",
		permissions_desc: "Har bir rol uchun ruxsatlar matritsasi",
		permission: "Ruxsat",
		perm_manage_users: "Foydalanuvchilarni boshqarish",
		perm_manage_settings: "Sozlamalarni boshqarish",
		perm_manage_teachers: "O'qituvchilarni boshqarish",
		perm_view_activities: "Barcha faoliyatlarni ko'rish",
		perm_submit_activities: "Faoliyat kiritish",
		perm_approve_activities: "Faoliyat tasdiqlash",
		perm_view_reports: "Hisobotlarni ko'rish",
		perm_export_data: "Ma'lumotlarni eksport qilish",
		audit_log_tab: "O'zgarishlar tarixi",
		audit_log_desc: "Tizimdagi barcha o'zgarishlar jurnali",
		no_audit_logs: "O'zgarishlar tarixi bo'sh",
		audit_log_empty_desc: "Tizimda hali hech qanday o'zgarish qayd etilmagan",
		save_settings: "Saqlash",
		settings_saved: "Sozlamalar saqlandi",
		add: "Qo'shish",
		add_role: "Yangi rol qo'shish",
		edit_role: "Rolni tahrirlash",
		delete_role: "Rolni o'chirish",
		delete_role_desc: "'{0}' rolini o'chirishni xohlaysizmi? Bu amal qaytarib bo'lmaydi.",
		role_name: "Rol nomi",
		delete: "O'chirish",
		cancel: "Bekor qilish",
		save: "Saqlash",
		saved: "Saqlandi",
		deleted: "O'chirildi",
		permissions_count: "ta ruxsat",
		add_type: "Yangi tur qo'shish",
		edit_type: "Turni tahrirlash",
		delete_type: "Turni o'chirish",
		delete_type_desc: "'{0}' turini o'chirishni xohlaysizmi?",
		add_year: "Yangi o'quv yili qo'shish",
		edit_year: "O'quv yilini tahrirlash",
		delete_year: "O'quv yilini o'chirish",
		delete_year_desc: "'{0}' o'quv yilini o'chirishni xohlaysizmi?",
		add_category: "Yangi kategoriya qo'shish",
		edit_category: "Kategoriyani tahrirlash",
		delete_category: "Kategoriyani o'chirish",
		delete_category_desc: "'{0}' kategoriyasini o'chirishni xohlaysizmi?",
		add_item: "Yangi qo'shish",
		edit_item: "Tahrirlash",
		delete_item: "O'chirish",
		delete_item_desc: "'{0}' yozuvini o'chirishni xohlaysizmi?",
		academic_degree_sg: "Ilmiy daraja",
		academic_rank_sg: "Ilmiy unvon",
		abbreviation: "Qisqartma",
		no_roles: "Rollar mavjud emas",
		no_roles_desc: "Avval rollar bo'limida yangi rol qo'shing",
		active: "Faol",
		inactive: "Nofaol",
		is_active: "Faol",
		is_penalty: "Jarima",
		base_score: "Asosiy ball",
		multiplier: "Ko'paytiruvchi",
		max_score: "Maksimal ball",
		name_field: "Nomi",
		start_date: "Boshlanish sanasi",
		end_date: "Tugash sanasi",
		group: "Guruh",
		no_years: "O'quv yillari mavjud emas",
		points: "ball",
		no_data: "Ma'lumot yo'q",
		description: "Tavsif",

		// Teacher navigation
		nav_home: "Bosh sahifa",
		nav_kpi_results: "KPI natijalarim",
		nav_add_result: "Yangi natija qo'shish",
		nav_my_scores: "Mening ballarim",
		nav_appeals: "Apellyatsiyalar",
		nav_notifications: "Xabarnomalar",
		teacher_help_title: "Yordam kerakmi?",
		teacher_help_desc: "Qo'llanma va tez-tez so'raladigan savollar",
		teacher_help_center: "Yordam markazi",
		academic_year_label: "Akademik yil",

		// Yes/No
		yes: "Ha",
		no: "Yo'q",
	},

	ru: {
		app_name: "KIUT",
		tagline: "Система рейтинга научной деятельности университета",
		univ_name_line1: "KIMYO INTERNATIONAL UNIVERSITY",
		univ_name_line2: "IN TASHKENT",

		dashboard: "Дашборд",
		teachers: "Преподаватели",
		activities: "Деятельность",
		review: "Проверка",
		rating: "Рейтинг",
		reports: "Отчеты",
		catalogs: "Каталоги",
		departments_page: "Кафедры",
		categories_page: "Категории",
		degrees: "Ученые степени",
		academic_years: "Учебные годы",
		system: "Система",
		public_rating: "Публичный рейтинг",
		settings: "Настройки",

		edit: "Редактировать",
		confirm: "Подтвердить",
		send: "Отправить",
		search: "Поиск...",
		search_by_name: "Поиск по имени...",
		all: "Все",
		clear: "Очистить",
		score: "Балл",
		status: "Статус",
		actions: "Действие",
		select: "Выбрать",
		loading: "Загрузка...",
		data_not_found: "Данные отсутствуют",
		filter: "Фильтр",
		view: "Просмотр",

		all_statuses: "Все",
		draft: "Черновик",
		submitted: "Отправлено",
		in_review: "На проверке",
		revision: "Доработка",
		approved: "Одобрено",
		rejected: "Отклонено",
		archived: "Архивировано",
		pending: "Ожидающие",
		reviewed: "Проверенные",

		teachers_title: "Преподаватели",
		teachers_desc: "Управление списком преподавателей",
		add_teacher: "Добавить",
		new_teacher: "Новый преподаватель",
		edit_teacher: "Редактировать",
		full_name: "Полное имя",
		department: "Кафедра",
		all_departments: "Все кафедры",
		position: "Должность",
		all_positions: "Все должности",
		academic_degree: "Ученая степень",
		all_degrees: "Все степени",
		academic_rank: "Ученое звание",
		employment_type: "Тип занятости",
		email: "Email",
		phone: "Телефон",
		photo: "Фото",
		upload_photo: "Загрузить фото",
		change_photo: "Изменить фото",
		score_range: "Балл",
		teacher_added: "Преподаватель добавлен",
		teacher_updated: "Преподаватель обновлен",
		no_teachers: "Преподаватели не найдены",
		no_teachers_desc: "Добавьте нового преподавателя",
		shtat: "Штат",
		soatbay: "Почасовик",
		ichki_orindosh: "Внутр. совместитель",
		tashqi_orindosh: "Внеш. совместитель",

		activities_title: "Деятельность",
		activities_desc: "Управление научной и академической деятельностью",
		new_activity: "Новая деятельность",
		edit_activity: "Редактировать",
		activity_details: "Детали деятельности",
		title: "Заголовок",
		category: "Категория",
		date: "Дата",
		academic_year: "Учебный год",
		reference_url: "Ссылка (DOI, URL)",
		reference_placeholder: "https://...",
		evidence: "Документы",
		evidence_files: "Документы (Evidence)",
		click_to_upload: "Нажмите для загрузки файла",
		file_types_hint: "PDF, DOCX, JPG, PNG, XLSX",
		coauthor: "Соавторство (50% коэффициент)",
		coauthor_name: "Имя и фамилия соавтора",
		coauthor_placeholder: "Полное имя соавтора",
		submit_for_review: "Отправить",
		activity_added: "Деятельность добавлена",
		activity_updated: "Деятельность обновлена",
		submitted_to_review: "Отправлено на проверку",
		no_activities: "Деятельность не найдена",
		no_activities_desc: "Добавьте новую деятельность",
		teacher: "Преподаватель",
		final_score: "Итоговый балл",
		reviewer_comment: "Комментарий проверяющего",
		submitted_by_teacher: "Отправлено преподавателем",
		coauthor_label: "Соавторство",
		files_count: "док.",
		files: "Документы",

		review_title: "Проверка",
		review_desc: "Просмотр и утверждение деятельности",
		approve: "Одобрить",
		reject: "Отклонить",
		revision_action: "Правка",
		confirm_decision: "Подтвердите решение",
		confirm_approve: "Одобрить эту деятельность?",
		confirm_reject: "Отклонить эту деятельность?",
		confirm_revision: "Отправить на доработку?",
		comment: "Комментарий",
		comment_placeholder: "Введите комментарий...",
		review_success: "Успешно выполнено",
		no_pending: "Нет деятельности для проверки",

		reports_title: "Отчеты",
		reports_desc: "Статистические отчеты и аналитика",
		export_excel: "Excel",
		excel_exported: "Отчет экспортирован в CSV",
		no_export_data: "Нет данных для экспорта",
		departments_report: "Кафедры",
		categories_report: "Категории",
		statuses_report: "Статусы",
		teachers_count: "Преподаватели",
		activities_count: "Деятельность",
		approved_count: "Одобрено",
		avg_score: "Средний балл",
		dept_chart_title: "Баллы по кафедрам",
		cat_chart_title: "Деятельность по категориям",
		status_chart_title: "Распределение по статусам",
		year: "Год",
		month: "Месяц",
		quarter: "Квартал",
		week: "Неделя",
		all_years: "Все годы",
		all_months: "Все месяцы",
		all_quarters: "Все кварталы",
		all_weeks: "Все недели",
		count: "Кол-во",
		unknown: "Неизвестно",

		status_draft: "Черновик",
		status_submitted: "Отправлено",
		status_in_review: "На проверке",
		status_approved: "Одобрено",
		status_rejected: "Отклонено",
		status_revision: "Доработка",

		january: "Январь",
		february: "Февраль",
		march: "Март",
		april: "Апрель",
		may: "Май",
		june: "Июнь",
		july: "Июль",
		august: "Август",
		september: "Сентябрь",
		october: "Октябрь",
		november: "Ноябрь",
		december: "Декабрь",
		q1: "1-й квартал (Янв-Мар)",
		q2: "2-й квартал (Апр-Июн)",
		q3: "3-й квартал (Июл-Сен)",
		q4: "4-й квартал (Окт-Дек)",

		departments_title: "Кафедры",
		departments_desc: "Управление списком кафедр",
		new_department: "Новая кафедра",
		edit_department: "Редактировать",
		name: "Название",
		name_req: "Название *",
		code: "Код",
		head: "Заведующий",
		dep_added: "Кафедра добавлена",
		dep_updated: "Кафедра обновлена",
		dep_deleted: "Кафедра удалена",
		no_departments: "Кафедры не найдены",
		delete_confirm_title: "Подтвердить удаление?",
		delete_confirm_desc: "Это действие нельзя отменить.",
		head_label: "Зав.:",

		categories_title: "Категории",
		categories_desc: "Категории начисления баллов",
		new_category: "Новая категория",
		group_req: "Группа *",
		multiplier_field: "Множитель",
		penalty_yes: "Да",
		cat_added: "Категория добавлена",
		cat_updated: "Категория обновлена",
		cat_deleted: "Категория удалена",
		no_categories: "Категории не найдены",
		academic: "Академ.",
		qualification: "Квалиф.",
		scientific: "Научн.",
		other: "Прочее",
		group_academic_discipline: "Академическая дисциплина",
		group_qualification: "Квалификация и организация",
		group_scientific: "Научная деятельность",
		group_other: "Прочее",
		multiplier_short: "Множ.",
		max_short: "Макс.",
		penalty: "Штраф",

		degrees_title: "Ученые степени и звания",
		degrees_desc: "Управление каталогами",
		new_degree: "Новая степень",
		new_rank: "Новое звание",
		degrees_tab: "Ученые степени",
		ranks_tab: "Ученые звания",
		item_added: "Добавлено",
		item_updated: "Обновлено",
		item_deleted: "Удалено",

		years_title: "Учебные годы",
		years_desc: "Управление учебными годами",
		years_purpose: "Учебные годы используются для группировки деятельности по периодам. Каждая деятельность привязывается к конкретному учебному году.",
		new_year: "Новый учебный год",
		state: "Статус",
		active_state: "Активный",
		inactive_state: "Неактивный",
		year_placeholder: "2024-2025",
		year_added: "Учебный год добавлен",
		year_updated: "Учебный год обновлен",
		year_deleted: "Учебный год удален",
		start_label: "Начало",
		end_label: "Окончание",

		dashboard_title: "Главная",
		dashboard_desc: "Статистика научной деятельности университета",
		dashboard_desc_short: "Показатели научной деятельности по кафедрам",
		approved_stat: "Одобрено",
		total_score: "Всего баллов",
		dept_scores_chart: "Баллы по кафедрам",
		cat_distribution_chart: "Распределение категорий",
		pending_reviews: "Ожидающие проверки",
		no_pending_reviews: "Нет ожидающих проверок",
		recent_activities: "Последние деятельности",
		no_recent_activities: "Нет деятельности",

		rating_title: "Рейтинг",
		rating_desc: "Рейтинг преподавателей",
		rank_label: "Место",

		public_rating_title: "Рейтинг Университета",
		public_rating_desc: "Рейтинг научной деятельности преподавателей",
		public_search_placeholder: "Поиск по имени...",
		public_department_placeholder: "Кафедра",

		settings_title: "Настройки",
		settings_desc: "Системные настройки и панель управления",
		roles_tab: "Роли пользователей",
		roles_desc: "Существующие роли в системе и их обязанности",
		role_admin: "Администратор",
		role_admin_desc: "Полный доступ, может изменять все настройки",
		role_rector: "Ректор",
		role_rector_desc: "Принимает стратегические решения, видит все отчеты",
		role_dean: "Декан",
		role_dean_desc: "Управляет факультетом, имеет право утверждения",
		role_department_head: "Зав. кафедрой",
		role_department_head_desc: "Управляет деятельностью преподавателей кафедры",
		role_teacher: "Преподаватель",
		role_teacher_desc: "Вводит данные о деятельности и отслеживает свой рейтинг",
		role_reviewer: "Рецензент",
		role_reviewer_desc: "Проверяет и оценивает деятельности",
		kpi_calc_tab: "Расчет KPI",
		kpi_calc_title: "Параметры расчета KPI",
		calc_mode: "Режим расчета",
		calc_auto: "Автоматический",
		calc_manual: "Ручной",
		score_scale_max: "Максимальная шкала баллов",
		weight_percentages: "Вес направлений (в процентах)",
		weight_teaching: "Преподавание",
		weight_scientific: "Научная деятельность",
		weight_methodical: "Методическая работа",
		weight_grants: "Гранты",
		weight_publications: "Публикации",
		weight_supervision: "Руководство",
		kpi_period_start: "Начало периода KPI",
		kpi_period_end: "Конец периода KPI",
		auto_approve_threshold: "Порог автоутверждения",
		auto_approve_desc: "Деятельности с баллом выше этого значения утверждаются автоматически (0 = отключено)",
		teacher_types_tab: "Типы преподавателей",
		teacher_types_desc: "Типы занятости преподавателей",
		shtat_desc: "Основной сотрудник на полной ставке",
		soatbay_desc: "Почасовой преподаватель",
		ichki_orindosh_desc: "Внутренний совместитель",
		tashqi_orindosh_desc: "Внешний совместитель",
		academic_years_tab: "Учебные годы",
		academic_year_settings_desc: "Список текущих учебных годов. Деятельности группируются по периодам.",
		manage_academic_years: "Управление учебными годами",
		categories_tab: "Категории KPI",
		categories_settings_desc: "Типы деятельности и их балльные значения",
		manage_categories: "Управление категориями",
		degrees_settings_desc: "Список ученых степеней и званий",
		academic_degrees: "Ученые степени",
		academic_ranks: "Ученые звания",
		manage_degrees: "Управление степенями и званиями",
		dashboard_settings_tab: "Настройки дашборда",
		dashboard_settings_desc: "Внешний вид и функции главной страницы",
		show_charts: "Показывать графики",
		show_charts_desc: "Графики статистики по кафедрам и категориям",
		show_filters: "Панель фильтров",
		show_filters_desc: "Возможности фильтрации в отчетах",
		enable_export: "Функция экспорта",
		enable_export_desc: "Скачивание данных в формате CSV",
		notifications_tab: "Уведомления",
		notifications_desc: "Системные уведомления и оповещения",
		deadline_reminder: "Напоминание о сроках",
		deadline_reminder_desc: "Уведомление при приближении срока сдачи KPI",
		approval_notify: "Уведомления об утверждении",
		approval_notify_desc: "Уведомление при утверждении или отклонении деятельности",
		warning_notify: "Предупреждения",
		warning_notify_desc: "Предупреждения о низких баллах или просроченных деятельностях",
		permissions_tab: "Разрешения",
		permissions_desc: "Матрица разрешений для каждой роли",
		permission: "Разрешение",
		perm_manage_users: "Управление пользователями",
		perm_manage_settings: "Управление настройками",
		perm_manage_teachers: "Управление преподавателями",
		perm_view_activities: "Просмотр всех деятельностей",
		perm_submit_activities: "Подача деятельности",
		perm_approve_activities: "Утверждение деятельности",
		perm_view_reports: "Просмотр отчетов",
		perm_export_data: "Экспорт данных",
		audit_log_tab: "История изменений",
		audit_log_desc: "Журнал всех изменений в системе",
		no_audit_logs: "История изменений пуста",
		audit_log_empty_desc: "В системе пока не зарегистрировано никаких изменений",
		save_settings: "Сохранить",
		settings_saved: "Настройки сохранены",
		add: "Добавить",
		add_role: "Добавить роль",
		edit_role: "Редактировать роль",
		delete_role: "Удалить роль",
		delete_role_desc: "Вы уверены, что хотите удалить роль '{0}'? Это действие необратимо.",
		role_name: "Название роли",
		delete: "Удалить",
		cancel: "Отмена",
		save: "Сохранить",
		saved: "Сохранено",
		deleted: "Удалено",
		permissions_count: "разрешений",
		add_type: "Добавить тип",
		edit_type: "Редактировать тип",
		delete_type: "Удалить тип",
		delete_type_desc: "Удалить тип '{0}'?",
		add_year: "Добавить учебный год",
		edit_year: "Редактировать учебный год",
		delete_year: "Удалить учебный год",
		delete_year_desc: "Удалить учебный год '{0}'?",
		add_category: "Добавить категорию",
		edit_category: "Редактировать категорию",
		delete_category: "Удалить категорию",
		delete_category_desc: "Удалить категорию '{0}'?",
		add_item: "Добавить",
		edit_item: "Редактировать",
		delete_item: "Удалить",
		delete_item_desc: "Удалить запись '{0}'?",
		academic_degree_sg: "Ученая степень",
		academic_rank_sg: "Ученое звание",
		abbreviation: "Аббревиатура",
		no_roles: "Роли отсутствуют",
		no_roles_desc: "Сначала добавьте роль в разделе ролей",
		active: "Активен",
		inactive: "Неактивен",
		is_active: "Активен",
		is_penalty: "Штраф",
		base_score: "Базовый балл",
		multiplier: "Множитель",
		max_score: "Макс. балл",
		name_field: "Название",
		start_date: "Дата начала",
		end_date: "Дата окончания",
		group: "Группа",
		no_years: "Учебные годы отсутствуют",
		points: "баллов",
		no_data: "Нет данных",
		description: "Описание",

		// Teacher navigation
		nav_home: "Главная",
		nav_kpi_results: "Мои KPI",
		nav_add_result: "Добавить результат",
		nav_my_scores: "Мои баллы",
		nav_appeals: "Апелляции",
		nav_notifications: "Уведомления",
		teacher_help_title: "Нужна помощь?",
		teacher_help_desc: "Руководство и часто задаваемые вопросы",
		teacher_help_center: "Центр помощи",
		academic_year_label: "Академический год",

		yes: "Да",
		no: "Нет",
		back: "Назад",
	},

	en: {
		app_name: "KIUT",
		tagline: "University Scientific Activity Rating System",
		univ_name_line1: "KIMYO INTERNATIONAL UNIVERSITY",
		univ_name_line2: "IN TASHKENT",

		dashboard: "Dashboard",
		teachers: "Teachers",
		activities: "Activities",
		review: "Review",
		rating: "Rating",
		reports: "Reports",
		catalogs: "Catalogs",
		departments_page: "Departments",
		categories_page: "Categories",
		degrees: "Academic Degrees",
		academic_years: "Academic Years",
		system: "System",
		public_rating: "Public Rating",
		settings: "Settings",

		edit: "Edit",
		confirm: "Confirm",
		send: "Submit",
		search: "Search...",
		search_by_name: "Search by name...",
		all: "All",
		clear: "Clear",
		score: "Score",
		status: "Status",
		actions: "Action",
		select: "Select",
		loading: "Loading...",
		data_not_found: "No data available",
		filter: "Filter",
		view: "View",

		all_statuses: "All",
		draft: "Draft",
		submitted: "Submitted",
		in_review: "In Review",
		revision: "Revision",
		approved: "Approved",
		rejected: "Rejected",
		archived: "Archived",
		pending: "Pending",
		reviewed: "Reviewed",

		teachers_title: "Teachers",
		teachers_desc: "Manage teacher list",
		add_teacher: "Add",
		new_teacher: "New Teacher",
		edit_teacher: "Edit Teacher",
		full_name: "Full Name",
		department: "Department",
		all_departments: "All Departments",
		position: "Position",
		all_positions: "All Positions",
		academic_degree: "Academic Degree",
		all_degrees: "All Degrees",
		academic_rank: "Academic Rank",
		employment_type: "Employment Type",
		email: "Email",
		phone: "Phone",
		photo: "Photo",
		upload_photo: "Upload Photo",
		change_photo: "Change Photo",
		score_range: "Score",
		teacher_added: "Teacher added",
		teacher_updated: "Teacher updated",
		no_teachers: "No teachers found",
		no_teachers_desc: "Add a new teacher",
		shtat: "Full-time",
		soatbay: "Hourly",
		ichki_orindosh: "Internal PT",
		tashqi_orindosh: "External PT",

		activities_title: "Activities",
		activities_desc: "Manage scientific and academic activities",
		new_activity: "New Activity",
		edit_activity: "Edit Activity",
		activity_details: "Activity Details",
		title: "Title",
		category: "Category",
		date: "Date",
		academic_year: "Academic Year",
		reference_url: "Reference (DOI, URL)",
		reference_placeholder: "https://...",
		evidence: "Documents",
		evidence_files: "Documents (Evidence)",
		click_to_upload: "Click to upload file",
		file_types_hint: "PDF, DOCX, JPG, PNG, XLSX",
		coauthor: "Co-authorship (50% coefficient)",
		coauthor_name: "Co-author Full Name",
		coauthor_placeholder: "Co-author full name",
		submit_for_review: "Submit",
		activity_added: "Activity added",
		activity_updated: "Activity updated",
		submitted_to_review: "Submitted for review",
		no_activities: "No activities found",
		no_activities_desc: "Add a new activity",
		teacher: "Teacher",
		final_score: "Final Score",
		reviewer_comment: "Reviewer Comment",
		submitted_by_teacher: "Submitted by teacher",
		coauthor_label: "Co-authorship",
		files_count: "docs",
		files: "Documents",

		review_title: "Review",
		review_desc: "Review and approve activities",
		approve: "Approve",
		reject: "Reject",
		revision_action: "Revise",
		confirm_decision: "Confirm Decision",
		confirm_approve: "Approve this activity?",
		confirm_reject: "Reject this activity?",
		confirm_revision: "Send for revision?",
		comment: "Comment",
		comment_placeholder: "Write a comment...",
		review_success: "Completed successfully",
		no_pending: "No activities for review",

		reports_title: "Reports",
		reports_desc: "Statistical reports and analytics",
		export_excel: "Excel",
		excel_exported: "Report exported to CSV",
		no_export_data: "No data available for export",
		departments_report: "Departments",
		categories_report: "Categories",
		statuses_report: "Statuses",
		teachers_count: "Teachers",
		activities_count: "Activities",
		approved_count: "Approved",
		avg_score: "Average Score",
		dept_chart_title: "Scores by Department",
		cat_chart_title: "Activities by Category",
		status_chart_title: "Distribution by Status",
		year: "Year",
		month: "Month",
		quarter: "Quarter",
		week: "Week",
		all_years: "All Years",
		all_months: "All Months",
		all_quarters: "All Quarters",
		all_weeks: "All Weeks",
		count: "Count",
		unknown: "Unknown",

		status_draft: "Draft",
		status_submitted: "Submitted",
		status_in_review: "In Review",
		status_approved: "Approved",
		status_rejected: "Rejected",
		status_revision: "Revision",

		january: "January",
		february: "February",
		march: "March",
		april: "April",
		may: "May",
		june: "June",
		july: "July",
		august: "August",
		september: "September",
		october: "October",
		november: "November",
		december: "December",
		q1: "1st Quarter (Jan-Mar)",
		q2: "2nd Quarter (Apr-Jun)",
		q3: "3rd Quarter (Jul-Sep)",
		q4: "4th Quarter (Oct-Dec)",

		departments_title: "Departments",
		departments_desc: "Manage department list",
		new_department: "New Department",
		edit_department: "Edit",
		name: "Name",
		name_req: "Name *",
		code: "Code",
		head: "Head",
		dep_added: "Department added",
		dep_updated: "Department updated",
		dep_deleted: "Department deleted",
		no_departments: "No departments found",
		delete_confirm_title: "Confirm deletion?",
		delete_confirm_desc: "This action cannot be undone.",
		head_label: "Head:",

		categories_title: "Categories",
		categories_desc: "Scoring categories",
		new_category: "New Category",
		group_req: "Group *",
		multiplier_field: "Multiplier",
		penalty_yes: "Yes",
		cat_added: "Category added",
		cat_updated: "Category updated",
		cat_deleted: "Category deleted",
		no_categories: "No categories found",
		academic: "Academic",
		qualification: "Qualif.",
		scientific: "Scientific",
		other: "Other",
		group_academic_discipline: "Academic Discipline",
		group_qualification: "Qualification & Organization",
		group_scientific: "Scientific Activity",
		group_other: "Other",
		multiplier_short: "Mult.",
		max_short: "Max",
		penalty: "Penalty",

		degrees_title: "Academic Degrees & Ranks",
		degrees_desc: "Manage catalogs",
		new_degree: "New Degree",
		new_rank: "New Rank",
		degrees_tab: "Academic Degrees",
		ranks_tab: "Academic Ranks",
		item_added: "Added",
		item_updated: "Updated",
		item_deleted: "Deleted",

		years_title: "Academic Years",
		years_desc: "Manage academic years",
		years_purpose: "Academic years are used to group activities by periods. Each activity is linked to a specific academic year.",
		new_year: "New Academic Year",
		state: "Status",
		active_state: "Active",
		inactive_state: "Inactive",
		year_placeholder: "2024-2025",
		year_added: "Academic year added",
		year_updated: "Academic year updated",
		year_deleted: "Academic year deleted",
		start_label: "Start",
		end_label: "End",

		dashboard_title: "Home",
		dashboard_desc: "University scientific activity statistics",
		dashboard_desc_short: "Department scientific activity indicators",
		approved_stat: "Approved",
		total_score: "Total Score",
		dept_scores_chart: "Scores by Department",
		cat_distribution_chart: "Category Distribution",
		pending_reviews: "Pending Reviews",
		no_pending_reviews: "No pending reviews",
		recent_activities: "Recent Activities",
		no_recent_activities: "No activities",

		rating_title: "Rating",
		rating_desc: "Teacher Rating",
		rank_label: "Rank",

		public_rating_title: "University Rating",
		public_rating_desc: "Teacher Scientific Activity Rating",
		public_search_placeholder: "Search by name...",
		public_department_placeholder: "Department",

		settings_title: "Settings",
		settings_desc: "System settings and management panel",
		roles_tab: "User Roles",
		roles_desc: "Available roles in the system and their responsibilities",
		role_admin: "Administrator",
		role_admin_desc: "Full access, can modify all settings",
		role_rector: "Rector",
		role_rector_desc: "Makes strategic decisions, views all reports",
		role_dean: "Dean",
		role_dean_desc: "Manages faculty, has approval rights",
		role_department_head: "Department Head",
		role_department_head_desc: "Manages department teacher activities",
		role_teacher: "Teacher",
		role_teacher_desc: "Submits activity data and tracks own rating",
		role_reviewer: "Reviewer",
		role_reviewer_desc: "Reviews and evaluates activities",
		kpi_calc_tab: "KPI Calculation",
		kpi_calc_title: "KPI Calculation Parameters",
		calc_mode: "Calculation Mode",
		calc_auto: "Automatic",
		calc_manual: "Manual",
		score_scale_max: "Maximum Score Scale",
		weight_percentages: "Category Weights (percentage)",
		weight_teaching: "Teaching",
		weight_scientific: "Scientific Activity",
		weight_methodical: "Methodical Work",
		weight_grants: "Grants",
		weight_publications: "Publications",
		weight_supervision: "Supervision",
		kpi_period_start: "KPI Period Start",
		kpi_period_end: "KPI Period End",
		auto_approve_threshold: "Auto-approve Threshold",
		auto_approve_desc: "Activities above this score are auto-approved (0 = disabled)",
		teacher_types_tab: "Teacher Types",
		teacher_types_desc: "Teacher employment categories",
		shtat_desc: "Full-time permanent staff member",
		soatbay_desc: "Hourly-paid teacher",
		ichki_orindosh_desc: "Internal part-time employee",
		tashqi_orindosh_desc: "External part-time employee",
		academic_years_tab: "Academic Year Settings",
		academic_year_settings_desc: "List of current academic years. Activities are grouped by periods.",
		manage_academic_years: "Manage Academic Years",
		categories_tab: "KPI Categories",
		categories_settings_desc: "Activity types and their score values",
		manage_categories: "Manage Categories",
		degrees_settings_desc: "Academic degrees and titles list",
		academic_degrees: "Academic Degrees",
		academic_ranks: "Academic Titles",
		manage_degrees: "Manage Degrees & Titles",
		dashboard_settings_tab: "Dashboard Settings",
		dashboard_settings_desc: "Home page appearance and features",
		show_charts: "Show Charts",
		show_charts_desc: "Department and category statistics charts",
		show_filters: "Filter Panel",
		show_filters_desc: "Filtering capabilities in reports",
		enable_export: "Export Function",
		enable_export_desc: "Download data in CSV format",
		notifications_tab: "Notifications",
		notifications_desc: "System notifications and alerts",
		deadline_reminder: "Deadline Reminders",
		deadline_reminder_desc: "Notify when KPI submission deadline approaches",
		approval_notify: "Approval Notifications",
		approval_notify_desc: "Notify when activities are approved or rejected",
		warning_notify: "Warnings",
		warning_notify_desc: "Warnings about low scores or overdue activities",
		permissions_tab: "Permissions",
		permissions_desc: "Permission matrix for each role",
		permission: "Permission",
		perm_manage_users: "Manage Users",
		perm_manage_settings: "Manage Settings",
		perm_manage_teachers: "Manage Teachers",
		perm_view_activities: "View All Activities",
		perm_submit_activities: "Submit Activities",
		perm_approve_activities: "Approve Activities",
		perm_view_reports: "View Reports",
		perm_export_data: "Export Data",
		audit_log_tab: "Audit Log",
		audit_log_desc: "Journal of all system changes",
		no_audit_logs: "Audit log is empty",
		audit_log_empty_desc: "No changes have been recorded in the system yet",
		save_settings: "Save",
		settings_saved: "Settings saved",
		add: "Add",
		add_role: "Add Role",
		edit_role: "Edit Role",
		delete_role: "Delete Role",
		delete_role_desc: "Are you sure you want to delete the role '{0}'? This action cannot be undone.",
		role_name: "Role Name",
		delete: "Delete",
		cancel: "Cancel",
		save: "Save",
		saved: "Saved",
		deleted: "Deleted",
		permissions_count: "permissions",
		add_type: "Add Type",
		edit_type: "Edit Type",
		delete_type: "Delete Type",
		delete_type_desc: "Delete type '{0}'?",
		add_year: "Add Academic Year",
		edit_year: "Edit Academic Year",
		delete_year: "Delete Academic Year",
		delete_year_desc: "Delete academic year '{0}'?",
		add_category: "Add Category",
		edit_category: "Edit Category",
		delete_category: "Delete Category",
		delete_category_desc: "Delete category '{0}'?",
		add_item: "Add",
		edit_item: "Edit",
		delete_item: "Delete",
		delete_item_desc: "Delete record '{0}'?",
		academic_degree_sg: "Academic Degree",
		academic_rank_sg: "Academic Rank",
		abbreviation: "Abbreviation",
		no_roles: "No roles available",
		no_roles_desc: "Add a role in the Roles section first",
		active: "Active",
		inactive: "Inactive",
		is_active: "Active",
		is_penalty: "Penalty",
		base_score: "Base Score",
		multiplier: "Multiplier",
		max_score: "Max Score",
		name_field: "Name",
		start_date: "Start Date",
		end_date: "End Date",
		group: "Group",
		no_years: "No academic years",
		points: "points",
		no_data: "No data",
		description: "Description",

		// Teacher navigation
		nav_home: "Home",
		nav_kpi_results: "My KPI Results",
		nav_add_result: "Add New Result",
		nav_my_scores: "My Scores",
		nav_appeals: "Appeals",
		nav_notifications: "Notifications",
		teacher_help_title: "Need Help?",
		teacher_help_desc: "Guide and frequently asked questions",
		teacher_help_center: "Help Center",
		academic_year_label: "Academic Year",

		yes: "Yes",
		no: "No",
		back: "Back",
	},
};

export const LanguageContext = createContext();

export function useLanguage() {
	const context = useContext(LanguageContext);
	if (!context) throw new Error("useLanguage must be used within LanguageProvider");
	return context;
}

export { translations };